language: java
sudo: false

jdk:
  - oraclejdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew
  - ./gradlew wrapper

script:
  - ./gradlew clean
  - ./gradlew build
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)